services:
  tkmk-prometheus:
    image: prom/prometheus
    user: root
    container_name: tkmk-prometheus
    ports:
      - 28001:9090 # 自分たちが割り振られている範囲のhostport:containerport
    volumes:
      - ./prom_config:/etc/prometheus/
      - metrics_data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml" # これ追加しないとloaderrorが出る
      - "--storage.tsdb.retention.time=7d" # データ保持期間 resource管理のみなので
    restart: always
    networks:
      - monitoring_default
  grafana:
    # image: grafana/grafana
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - 28002:3000   # 自分たちが割り振られている範囲のhostport:containerport

    volumes:
      # - ./grafana/dashboard:/var/lib/grafana/dashboards
      # - ./grafana/config/***.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    restart: always
    # entrypoint: "bash /var/lib/grafana/dashboards/json_sub.sh"
    # environment:
      # - DS_PROMETHEUS=prometheus-server-uid # uid設定の変数

    networks:
      - monitoring_default

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager # Configuration file
    
    command:
      - "--config.file=/etc/alertmanager/alert-config.yml" # See GitHub : https://github.com/prometheus/alertmanager
      - "--log.level=debug"
    expose:
      - '9093'
    restart: always
    networks:
      - monitoring_default

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - '9100'
    networks:
      - monitoring_default
  gpu-exporter:
    image: utkuozdemir/nvidia_gpu_exporter:1.1.0
    # build:
    #   context: .
    #   dockerfile: nvidia_gpu_exporter/Dockerfile
    container_name: nvidia-smi-exporter
    expose:
      - '9835'
        #ports: 
        # - '28004:9835' # host:28004
    restart: unless-stopped
    networks:
      - monitoring_default
    devices:
     - /dev/nvidiactl:/dev/nvidiactl
     - /dev/nvidia0:/dev/nvidia0
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
    # いらない
    # deploy:
    #   resources:
    #     limits:
    #       memory: 500M
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities:
    #             - gpu

volumes:
  metrics_data:
    name: metrics_data
    # external: true

networks:
  monitoring_default:
    external: true


